### ISSUE TITLE
PaddedMatrices PtrArray 

### ISSUE THREAD

**Issue by spinkney** [chriselrod/PaddedMatrices.jl#1]
Not sure if this is the appropriate place to ask, running the example in https://bayeswatch.org/2019/04/18/probability-models-hierarchical-example/ at chains1, tuned_samplers1 = NUTS_init_tune_mcmc_default(ℓ_itp, 2000, δ = 0.75); I get the following error in PaddedMatrices regarding the PtrArray. This is way beyond my Julia skills, hopefully you can help. 

I know everything is in dev but would love to get this example working. I want to test a similar Stan program I have and see if the speed up is significant.

Thanks!

```julia
MethodError: no method matching PaddedMatrices.PtrArray{Tuple{24,9},NTuple{4,VecElement{Float64}},2,24,216,P} where P(::Ptr{Float64})
in top-level scope at base\util.jl:156
in  at base\none
in #NUTS_init_tune_mcmc_default#80 at ProbabilityModels\eacGe\src\dynamic_hmc_interface.jl:1001 
in #NUTS_init_tune_mcmc_default at base\none 
in #NUTS_init_tune_mcmc_default#79 at ProbabilityModels\eacGe\src\dynamic_hmc_interface.jl:997
in NUTS_init at ProbabilityModels\eacGe\src\dynamic_hmc_interface.jl:982
in #NUTS_init#77 at ProbabilityModels\eacGe\src\dynamic_hmc_interface.jl:983
in phasepoint_in at DynamicHMC\YX6JA\src\hamiltonian.jl:149 
in logdensity at ProbabilityModels\eacGe\src\model_macro_passes.jl:571
in macro expansion at ProbabilityModels\eacGe\src\model_macro_passes.jl:256 
in ∂Normal at ProbabilityDistributions\r10W5\src\normal_distribution.jl:768
in macro expansion at ProbabilityDistributions\r10W5\src\normal_distribution.jl:742 
in vload at ScatteredArrays\A36th\src\chunked_struct_array.jl:181
in macro expansion at ScatteredArrays\A36th\src\chunked_struct_array.jl:181 
REPL

```

```julia
# Load the following on master and all children
using DistributionParameters, ProbabilityDistributions
using LoopVectorization, DynamicHMC, LogDensityProblems, SLEEFPirates, SIMDPirates
using LinearAlgebra, StructuredMatrices, ScatteredArrays, PaddedMatrices
using ProbabilityModels
using DistributionParameters: LKJ_Correlation_Cholesky
using ProbabilityModels: Domains, HierarchicalCentering, ∂HierarchicalCentering, ITPExpectedValue, ∂ITPExpectedValue
BLAS.set_num_threads(1)


# Define the model on master and all children.
@model ITPModel begin

    # Non-hierarchical Priors
    (0.5ρ + 0.5) ~ Beta(2, 2)
    κ ~ Gamma(0.1, 0.1) # μ = 1, σ² = 10
    σ ~ Gamma(1.5, 0.25) # μ = 6, σ² = 2.4
    θ ~ Normal(10)
    L ~ LKJ(2.0)

    # Hierarchical Priors.
    # h subscript, for highest in the hierarhcy.
    μₕ₁ ~ Normal(10) # μ = 0
    μₕ₂ ~ Normal(10) # μ = 0
    σₕ ~ Normal(10) # μ = 0
    # Raw μs; non-cenetered parameterization
    μᵣ₁ ~ Normal() # μ = 0, σ = 1
    μᵣ₂ ~ Normal() # μ = 0, σ = 1
    # Center the μs
    μᵦ₁ = HierarchicalCentering(μᵣ₁, μₕ₁, σₕ)
    μᵦ₂ = HierarchicalCentering(μᵣ₂, μₕ₂, σₕ)
    σᵦ ~ Normal(10) # μ = 0
    # Raw βs; non-cenetered parameterization
    βᵣ₁ ~ Normal()
    βᵣ₂ ~ Normal()
    # Center the βs.
    β₁ = HierarchicalCentering(βᵣ₁, μᵦ₁, σᵦ, domains)
    β₂ = HierarchicalCentering(βᵣ₂, μᵦ₂, σᵦ, domains)

    U = inv′(Diagonal(σ) * L)

    # Likelihood
    μ₁ = ITPExpectedValue(t, β₁, κ, θ)
    μ₂ = ITPExpectedValue(t, β₂, κ, θ)
    AR = AutoregressiveMatrix(ρ, δₜ)
    Y₁ ~ Normal(μ₁, AR, U)
    Y₂ ~ Normal(μ₂, AR, U)

end

domains = Domains(2,2,2,3)
K, D = sum(domains), length(domains)

κ = (1/32) * reduce(+, (@Constant randexp(K)) for i ∈ 1:8) # κ ~ Gamma(8, 32)
σd = sum(@Constant randexp(4)) / 16 # σd ~ Gamma(4,16)
θ = 2.0 * (@Constant randn(K)) # θ ~ Normal(0,2)
S = (@Constant randn(K,4K)) |> x -> x * x'
S *= (1/16)
pS = StructuredMatrices.SymmetricMatrixL(S)
L = PaddedMatrices.chol(S); U = PaddedMatrices.invchol(pS)
μₕ₁, μₕ₂ = -3.0, 9.0
μᵦ₁ = μₕ₁ + @Constant randn(D); # placebo
μᵦ₂ = μₕ₂ + @Constant randn(D); #treatment
β₁ = HierarchicalCentering((@Constant randn(K)), μᵦ₁, σd, domains); # placebo
β₂ = HierarchicalCentering((@Constant randn(K)), μᵦ₂, σd, domains); # treatment

# rand generates uniform(0,1); we take the cumulate sum for the times.
T = 24; δₜ = (1/16) * reduce(+, (@Constant randexp(T-1)) for i ∈ 1:8)
times = vcat(zero(ConstantFixedSizePaddedVector{1,Float64}), cumsum(δₜ));

μ₁ = ITPExpectedValue(times, β₁, κ, θ)
μ₂ = ITPExpectedValue(times, β₂, κ, θ)

ρ = 0.7
ARcorrelation = StructuredMatrices.AutoregressiveMatrix(ρ, δₜ)
ARcholesky = PaddedMatrices.chol(ConstantFixedSizePaddedMatrix(ARcorrelation))
# Create an Array of matrix-normal entries.
Y₁a = [ARcholesky * (@Constant randn(T, K)) * L' + μ₁ for n in 1:120]
Y₂a = [ARcholesky * (@Constant randn(T, K)) * L' + μ₂ for n in 1:120]
Y₁ = ChunkedArray(Y₁a) # Rearranges how the data is stored under the hood.
Y₂ = ChunkedArray(Y₂a) # This often allows for better vectorization.

ℓ_itp = ITPModel(
    domains = domains, Y₁ = Y₁, Y₂ = Y₂, t = times, δₜ = δₜ,
    L = LKJ_Correlation_Cholesky{K}, ρ = BoundedFloat{-1,1},
    κ = PositiveVector{K}, θ = RealVector{K},
    μₕ₁ = RealFloat, μₕ₂ = RealFloat,
    μᵣ₁ = RealVector{D}, μᵣ₂ = RealVector{D},
    βᵣ₁ = RealVector{K}, βᵣ₂ = RealVector{K},
    σᵦ = PositiveFloat, σₕ = PositiveFloat,
    σ = PositiveVector{K}
);
@time chains1, tuned_samplers1 = NUTS_init_tune_mcmc_default(ℓ_itp, 2000, δ = 0.75);
```

**Comment by chriselrod** [comment]
Thanks for the bug report!

I fixed the problem [here](https://github.com/chriselrod/ScatteredArrays.jl/commit/5f94b4d03a741eb8ecb4405a159891345b7e0675) (in ScatteredArrays.jl, so that is the library that will need to be updated) that was introduced with [this commit](https://github.com/chriselrod/PaddedMatrices.jl/commit/9539ca59c96fcabaa8004ac1574d573c7580ec37#diff-3aa990cd290942410913de7b42928188R227).

In the breaking commit, I added an extra parameter to the `PtrArray` type. That parameter indicates whether or not that PtrArray is "padded".
For example, say we have a 7x7 PtrArray pointing to 8*7=56 doubles of memory, with a stride of 8 between columns.
If the last "padded" parameter is true, then 8th row will be treated as irrelevant junk that can be ignored and overwritten at will. Having it enables vectorization. With avx2, a column can be loaded into/stored from 2 registers (both holding 4 elements) instead of 3 (4, 2, and 1).

If the padded parameter is false, then the last row will be preserved via masking. Masks are fast with avx512, but slow otherwise. Which is why I have the option to overwrite them.
But if the PtrArray is being used as a non-allocating view of a larger array, we probably don't want to accidentally overwrite any elements outside of the view.

I didn't provide a default argument for the new parameter, hence the error.

In the ScatteredArrays case, the view doesn't bleed over, so I set it to true.
Perhaps I'll choose a default (probably "false") in PaddedMatrices, but for now I'll leave it explicit.


Please let me know if you have any more problems!

The library is definitely a WIP / very alpha at the moment.
It is very limited in features: no broadcasting, if/else statements, or loops.

My next major commits will add broadcasting support. I think broadcasting is expressive enough to cover a lot of possible models.
From there I'll probably add helper functions that work within the broadcasting / expression template framework to try and cover more models.

In my most recent tests, Zygote still seemed slow. But I also intend to support having that as a fallback for sections that aren't differentiated.

Please let me know if/when you run into any more problems!

**Comment by RoyiAvital** [comment]
@chriselrod , The documentation links doesn't work (Empty page).

I saw the comparison in https://bayeswatch.org/2019/06/06/small-matrix-multiplication-performance-shootout/.
Any chance you display results in graphs?

**Comment by chriselrod** [comment]
I'd probably want to rerun them using LoopVectorization. I've since removed almost all the old code from PaddedMatrices.

From the link you posted on discourse, it looks like using the API (which I didn't do) yields much better performance. If you want to write C or Fortran code using that API and a Julia interface, I could run them. 

A problem with plotting is that I benchmarked for many combinations of `M` and `N` for `M x 32` matrix `A`  times `32 x N` matriz `B`. Would you want me to make 32 plots, one for each value of `M`?

I think a different issue would be a more appropriate place to discuss this.

**Comment by RoyiAvital** [comment]
I'd be happy to see some graph comparing. No need for them all. Just few representative to see the order.

The main idea was to point you the Documentation links (https://chriselrod.github.io/PaddedMatrices.jl/stable and https://chriselrod.github.io/PaddedMatrices.jl/latest) for this repository aren't working.
