### ISSUE TITLE
Move pure Julia matrix multiplication to Octavian.jl?

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/PaddedMatrices.jl#19]
As discussed in https://github.com/MasonProtter/Gaius.jl/pull/63#issuecomment-753973835

**Comment by chriselrod** [comment]
The main problem is type piracy. The multiplication uses `PtrArray`s internally.
Seems like it's better for the array type definition to live with the matmul definition.

Meaning this would probably mean copying the `PtrArray` definition to Octavian, so that both libraries can have separate definitions they can define methods for without committing type piracy.

Although Octavian already has a definition, and doesn't need nearly so many methods, so that's probably fine.

Actually, I've been progressively moving toward using the abstract strided pointers without the array wrappers internally anyway.

**Comment by chriselrod** [comment]
The secondary issue is that the library has been aggressively experimental. Looking at contributors shows that my contributions to padded matrices are +30_000/-25_000 lines of code. That's a lot of churn, and I have again a fairly substantial overhaul of many of the blocking changes locally I was going to work on tonight (once those are done, I'll publish benchmarks and issue a release).
It's been a library for quickly iterating on and trying out different ideas related to arrays.
Padded matrices are no longer even a feature of PaddedMatrices.jl any more than they are of `Base.Array`; quick evolution has been it's thing.

So I'd be happy with copying the matrix multiplication over to Octavian (after I finish the blocking overhaul!), but it'd probably take me a little while to actually remove the implementation from this library and start depending on Octavian. It'd at least take me until after Octavian get's registered ;).

**Comment by DilumAluthge** [comment]
> but it'd probably take me a little while to actually remove the implementation from this library and start depending on Octavian

I think this is the more useful approach. Copying the matrix multiplication to Octavian is nice, but I think it's going to be more useful if we can set up a modular approach in which:
- Octavian is for rapid iteration of ideas related to pure Julia matrix multiplication (i.e. pure Julia BLAS)
- PaddedMatrices is for rapid iteration of other array-related ideas
- PaddedMatrices depends on Octavian and uses Octavian for matrix multiplication

That way e.g. people can start depending on Octavian and using its matmul without needing to pull in the other stuff we work on in PaddedMatrices.

**Comment by DilumAluthge** [comment]
> It'd at least take me until after Octavian get's registered ;).

This particular hurdle is done now 😂

**Comment by DilumAluthge** [comment]
I'm going to close this because I think this is done now?
